version: '3.8'

services:
    redis:
        container_name: 'redis'
        image: redis
    server:
        container_name: 'server'
        build:
            context: './server'
        ports:
            - '3001:3001'
        # The entire folder as a bind mount.
        # Only for development purposes.
        volumes:
            - './server:/usr/src/app:ro'
        # Only start the server's container after
        # Redis has started.
        depends_on:
            - redis
    client:
        container_name: 'client'
        build:
            context: './client'
        ports:
            - '3000:3000'
        volumes:
            - './client/pages:/app/pages:ro'
            - '/app/node_modules'
        depends_on:
            - server
